services:
  - type: web
    name: a2s-backend
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_DRIVER
        value: org.postgresql.Driver
      - key: DB_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGINS
        sync: false
      - key: LLM_SERVICE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: web
    name: a2s-llm
    runtime: docker
    dockerfilePath: ./LLM/Dockerfile
    dockerContext: ./LLM
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: PORT
        value: "5001"
